version: '3'
services:
  # back:
  #   build:
  #     context: back
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db

  front:
    build:
      context: front
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: <your_user>
      POSTGRES_PASSWORD: <your_password>
      POSTGRES_DB: <your_database_name>
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
            - transcendence
networks:
    transcendence:
        # name: transcendence
        driver: bridge

volumes:
    db_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: /home/$USER/data/DB

